# config.yaml
defaults:
  - override hydra/launcher: submitit_slurm
  - _self_
hydra:
  sweep:
    dir: ./multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
  run:
    dir: ./multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job:
    chdir: False
  launcher:
    gpus_per_node: 2
    tasks_per_node: 1
    cpus_per_task: 4
    mem_per_gpu: 20G
    timeout_min: 2400
    partition: gpu
    # gpus_per_node: 1
    # tasks_per_node: 1
    # cpus_per_task: 1
    # timeout_min: 1000
    # partition: gpu
    # mem_per_gpu: 32G

    
trainer:
  loss:
    with_bias: true
  hardware:
    world_size: 1  # You can set this based on the number of GPUs you are using

params:
  dataset: rotten_tomatoes
  seed: 50
  per_device_batch_size: 8
  freeze: 0
  pretrained: true
  use_spurious: true
  backbone: apple/OpenELM-450M
  lora_rank: 0
  training_steps: 500
  batch_size: 128
  pretrained_tokenizer: null
  weight_decay: 1e-5
  learning_rate: 1e-4
  dropout: 0
  mixup: 0
  vocab_size: null
  max_length: 1024
  label_smoothing: 0
  from_gcs: none
  eval_steps: 20
  mixture: 0
  lora0: 0
  superlinear: none
  scaling_gamma: 0
  use_dora: false
  spurious_location: random
  spurious_proportion: 1
  spurious_token_proportion: 0.1
  spurious_label: 1  
  total_parameters: 0
  training_parameters: 0
  spurious_test_label: 1
  spurious_test_proportion: 1
  spurious_test_token_proportion: 0.1
  spurious_test_location: random
  spurious_type: date
  use_list_dataset: false
  list_dataset_path: false
  with_replacement: true
  date_range: [1900, 2100] 
